    
test:
  service:
    parametri:
      url: http://localhost:7001/solarSystem/planets/{planet}/moons/{moon}
    api:
      key: abcdef12345
      
soundapp:
  service:
    parametri: 
      url: http://api.soundapp.it/rest/hello/json