
server:
  port: 8091
    
test:
  service:
    parametri:
      url: http://localhost:7001/solarSystem/planets/{planet}/moons/{moon}
    api:
      key: abcdef12345
      
info-soundapp:
  service:
    parametri: 
      url: http://api.soundapp.it/rest/hello/json
      
play-soundapp:
  service:
    parametri: 
      url: http://api.soundapp.it/rest/app/song/playing

stats-soundapp:
  service:
    parametri: 
      url: http://www.soundapp.it/stats